"""create saved table

Revision ID: c2efc020321e
Revises: ac6ad343928b
Create Date: 2022-05-20 16:03:23.748931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2efc020321e'
down_revision = 'ac6ad343928b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchased', sa.Boolean(), nullable=True),
    sa.Column('cartitem_id', sa.Integer(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('order_id', sa.Integer()),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('total', sa.Float(precision=4), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total')
    op.drop_table('saved_items')
    # ### end Alembic commands ###
